// GENERATED by scripts/build-api-docs.js — do not edit by hand.
// Cloudflare Pages Function — /api/opentelemetry-instrumentation-imqueue/*
// Retired slug: 301s /api/opentelemetry-instrumentation-imqueue/… onto /api/opentelemetry/latest/….
// See lib/api-redirects.js for the policy and why this is not in _redirects.
import { handleApiRequest } from "../../../lib/api-handler.js";

export const onRequest = handleApiRequest;
