name: imqueue.com
slogan: Intercommunication Messaging Queue For Microservices using Node and Typescript
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
