const yaml = require("js-yaml");
const syntaxHighlight = require("@11ty/eleventy-plugin-syntaxhighlight");

// ---- Edition switch -------------------------------------------------------
// One repo, two editions. Pick with EDITION=com|org (default: org).
//   EDITION=org  -> imqueue.org, "Terminal" skin, output _site-org
//   EDITION=com  -> imqueue.com, "Flux" skin,     output _site-com
const { buildAssetManifest } = require("./scripts/lib/asset-manifest.js");

const EDITION = (process.env.EDITION || "org").toLowerCase();
const isCom = EDITION === "com";
const SKIN = isCom ? "flux" : "terminal";
const SITE_URL = isCom ? "https://imqueue.com" : "https://imqueue.org";
const OTHER_URL = isCom ? "https://imqueue.org" : "https://imqueue.com";
const OUTPUT = isCom ? "_site-com" : "_site-org";

// Computed once at config time (sync fs reads) so the hashed names are available
// both to addPassthroughCopy and to the `asset` filter.
const ASSETS = buildAssetManifest(__dirname, EDITION);

module.exports = function (eleventyConfig) {
  const markdownIt = require("markdown-it");
  const mdAnchor = require("markdown-it-anchor");
  const mdToc = require("markdown-it-table-of-contents");
  const mdAttrs = require("markdown-it-attrs");

  // ---- heading ids ---------------------------------------------------------
  // markdown-it-anchor's DEFAULT slugify is
  // `encodeURIComponent(String(s).trim().toLowerCase().replace(/\s+/g, '-'))`,
  // which percent-encodes every character that is not URL-safe instead of
  // removing it. That produced 132 distinct ids across 72 built pages that no
  // human or model would ever reconstruct:
  //
  //   "Data & events"                -> data-%26-events
  //   "@classType() is now required" -> %40classtype()-is-now-required…
  //   "FilterInput.$eq property"     -> filterinput.%24eq-property
  //   "Can you use them together?"   -> can-you-use-them-together%3F
  //
  // Fragment citations are how an answer engine points at the specific paragraph
  // it used, and a model constructing one from a heading it can see produces the
  // conventional slug, not the percent-encoded one — so every deep citation into
  // this site landed on the top of the page instead of the section, and the
  // "On this page" sidebar (generated by markdown-it-table-of-contents through
  // this same function) shipped unreadable hrefs.
  //
  // Runs of anything that is not [a-z0-9] collapse to a single hyphen, which is
  // the shape of every hand-written anchor already in this repo. It is not
  // byte-identical to GitHub's rule (GitHub deletes the punctuation instead of
  // collapsing it, so "Data & events" becomes `data--events` with two hyphens) —
  // single-hyphen is both more guessable and what our own prose already uses.
  //
  // The empty-result fallback matters for a heading that is entirely punctuation
  // or non-Latin: an id of "" is invalid HTML and unlinkable. markdown-it-anchor
  // de-duplicates whatever comes back out of here, so two headings collapsing to
  // the same slug get `-1`, `-2` rather than colliding.
  const slugify = (s) => {
    const slug = String(s)
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");

    return slug || "section";
  };

  const md = markdownIt({ html: true, linkify: false, typographer: false })
    .use(mdAttrs)
    .use(mdAnchor, { permalink: false, tabIndex: false, slugify })
    .use(mdToc, {
      includeLevel: [2, 3],
      containerHeaderHtml: undefined,
      markerPattern: /^\[\[toc\]\]/im,
      // Must be the SAME function markdown-it-anchor got. Both plugins default
      // to their own copy of the encodeURIComponent slugifier, which is the only
      // reason the "On this page" hrefs matched the heading ids before; passing
      // it to one and not the other would silently break every TOC link.
      slugify,
    });

  eleventyConfig.setLibrary("md", md);
  eleventyConfig.addPlugin(syntaxHighlight);

  // Standard LiquidJS: quoted/variable partials + comma-separated include args.
  eleventyConfig.setLiquidOptions({
    dynamicPartials: true,
    jekyllInclude: false,
    strictFilters: false,
  });

  eleventyConfig.addDataExtension("yml", (contents) => yaml.load(contents));

  // Edition-wide values available in every template.
  eleventyConfig.addGlobalData("edition", EDITION);
  eleventyConfig.addGlobalData("skin", SKIN);
  eleventyConfig.addGlobalData("siteUrl", SITE_URL);
  eleventyConfig.addGlobalData("otherUrl", OTHER_URL);
  eleventyConfig.addGlobalData("siteName", "@imqueue");

  // ---- SEO defaults (per edition) -----------------------------------------
  // Page front matter can override `ogType`, `ogImage` and `description`; these
  // are the site-wide fallbacks head.html reaches for.
  //
  // There is no `siteKeywords` any more: it only ever fed <meta name="keywords">,
  // which Google has ignored since 2009. Per-page `keywords` front matter is
  // still read — post.html puts it in BlogPosting.keywords, which is a real
  // schema.org property.
  eleventyConfig.addGlobalData("siteImage", `${SITE_URL}/images/og-${EDITION}.png`);
  eleventyConfig.addGlobalData("siteLocale", "en_US");
  eleventyConfig.addGlobalData("themeColor", isCom ? "#0c0a17" : "#0a0e0d");
  eleventyConfig.addGlobalData("twitterHandle", "@imqueue");

  // ---- analytics (per edition, from the environment) -----------------------
  // These ids used to be hardcoded here, both editions sharing one GA4 property,
  // and the pair was wrong: the id in this file belongs to the property named
  // imqueue.com, so imqueue.org's traffic was recorded there while the property
  // named imqueue.org received nothing from the page. A repo cannot tell you which
  // property owns an id, which is exactly why they do not belong in a repo.
  //
  // Each Pages project now supplies its own, so the deployment is the single source
  // of truth and the two sites cannot silently share a property again:
  //
  //   GA4_MEASUREMENT_ID     G-… for THIS edition's property
  //   CLARITY_PROJECT_ID     Clarity project id for this edition
  //
  // Suffixed forms win when present (GA4_MEASUREMENT_ID_ORG / _COM), which is what
  // makes a local `npm run build:all` able to give each edition its own id in one
  // process. Unset means the tag is not emitted at all — so a local build, a fork
  // and a preview deploy send nothing to production analytics. That is a feature:
  // the previous arrangement had every `npm run serve:org` reporting as real traffic.
  // null, never "" — Liquid treats an empty string as TRUTHY, so `{% if analytics.ga4 %}`
  // in head.html would happily emit a tag with no id. Only nil and false are falsy there.
  const envId = (name) =>
    process.env[`${name}_${EDITION.toUpperCase()}`] || process.env[name] || null;

  // Correct per-edition ids, READ OUT OF GA4 ADMIN on 2026-08-02 (Admin → Data streams
  // → the stream → Measurement ID) rather than copied from the previous value here,
  // which was wrong: G-EQTNPY721G belongs to the property named imqueue.com, so
  // imqueue.org's traffic was recorded there and the property named imqueue.org got
  // none of it.
  //
  // These are the FALLBACK. An env var always wins, and the deployment should own
  // these values — but a Cloudflare Pages build was not receiving GA4_MEASUREMENT_ID
  // even when set as plaintext (both sites shipped with no tag at all), and an
  // env-only design means the site silently stops being measured whenever that
  // happens. These ids are public — they ship in every page's source — so the only
  // thing keeping them out of the repo was tidiness, and tidiness lost to a day of
  // lost analytics.
  const ANALYTICS_DEFAULTS = {
    org: { ga4: "G-CZ1JYCB5TK", clarity: "josp89y34k" },
    com: { ga4: "G-EQTNPY721G", clarity: "josp89y34k" },
  };

  // ...except under `npm run serve:*` / watch, where emitting the tag would report
  // local browsing as production traffic. That used to happen on every dev run, and
  // is part of why the org property reads 88.8% Direct. An explicit env var still
  // wins here, so measuring a local build stays possible on purpose.
  const isDevServer = ["serve", "watch"].includes(process.env.ELEVENTY_RUN_MODE);
  const fallback = isDevServer ? { ga4: null, clarity: null } : ANALYTICS_DEFAULTS[EDITION];

  const ANALYTICS = {
    ga4: envId("GA4_MEASUREMENT_ID") || fallback.ga4,
    clarity: envId("CLARITY_PROJECT_ID") || fallback.clarity,
  };

  for (const [key, value] of Object.entries(ANALYTICS)) {
    console.log(`[analytics] ${EDITION} ${key}: ${value || "not emitted"}`);
  }

  eleventyConfig.addGlobalData("analytics", ANALYTICS);

  // Full ISO 8601 for structured data and OG article timestamps. Schema.org and
  // Open Graph both want an unambiguous instant; the date-only "%Y-%m-%d" that
  // used to be emitted leaves the time zone to the consumer's guess.
  eleventyConfig.addFilter("isoDate", (value) => {
    const d = value instanceof Date ? value : new Date(value);
    return Number.isNaN(d.getTime()) ? "" : d.toISOString();
  });

  // Build only the active edition's pages.
  eleventyConfig.ignores.add(isCom ? "src/org/**" : "src/com/**");

  // Markdown content pages (docs/tutorial/cli/get-started) — used to emit
  // per-page ".md" mirrors, which is what AI agents read: the @imqueue MCP
  // server's get_doc fetches "<page-url>index.md".
  //
  // The generated API reference is included, but only its /latest/ pages.
  // Archived majors are left out deliberately: they are already noindex, and an
  // agent should never be handed a stale API surface.
  // The /api/ LANDING page is deliberately absent here even though it has a
  // markdown source. src/org/api/index.md is a Liquid template, not prose: its
  // body is a JSON-LD block, two card grids, a state-persistence <script> and
  // five `{% include %}`s that hold the actual guide. `rawInput` is none of
  // that, so md-mirror.liquid published the template source — including a
  // literal `"softwareVersion": "{{ latest_rpc }}"` — as the API reference an
  // agent reads. src/org/mirrors/api.liquid mirrors it by hand instead, on the
  // same model as the other authored mirrors, and includes the same guide
  // partials the HTML page and llms-full.txt do.
  const API_MIRRORED = /^\/api\/[^/]+\/latest\//;
  eleventyConfig.addCollection("contentMd", (api) =>
    api.getAll().filter((item) => {
      const url = item.url || "";

      if (!item.inputPath.endsWith(".md") || item.data.draft) {
        return false;
      }

      return url.includes("/api/") ? API_MIRRORED.test(url) : true;
    })
  );

  // Blog posts (.org only) — src/org/blog/posts/*.md, newest→oldest by date.
  // Drafts (front matter `draft: true`) build to their URL but are kept out of
  // the index listing.
  eleventyConfig.addCollection("posts", (api) =>
    api
      .getFilteredByGlob("src/org/blog/posts/*.md")
      .filter((item) => !item.data.draft)
      .sort((a, b) => b.date - a.date)
  );

  // Blog topic hubs (.org only). Posts already declare `topics:`, but nothing
  // turned that into pages, so the blog had no taxonomy: no intermediate pages
  // to pass link equity through, and 18 of 26 posts sat 3+ clicks from the home
  // page because /blog/ only surfaced the newest 8.
  //
  // A topic needs MIN_TOPIC_POSTS posts to get a hub. Below that a hub is one
  // link on a near-empty page, which is index bloat rather than a taxonomy.
  const MIN_TOPIC_POSTS = 3;
  eleventyConfig.addCollection("blogTopics", (api) => {
    const meta = require("./src/_data/blogTopics.json");
    const byTopic = new Map();

    for (const post of api
      .getFilteredByGlob("src/org/blog/posts/*.md")
      .filter((p) => !p.data.draft)
      .sort((a, b) => b.date - a.date)) {
      for (const slug of post.data.topics || []) {
        if (!byTopic.has(slug)) byTopic.set(slug, []);
        byTopic.get(slug).push(post);
      }
    }

    return [...byTopic.entries()]
      .filter(([slug, posts]) =>
        posts.length >= MIN_TOPIC_POSTS && meta[slug] && meta[slug].title)
      .map(([slug, posts]) => ({
        slug,
        posts,
        label: meta[slug].label,
        title: meta[slug].title,
        description: meta[slug].description,
      }))
      .sort((a, b) => b.posts.length - a.posts.length || a.slug.localeCompare(b.slug));
  });

  // ---- agent-facing markdown ----------------------------------------------
  // api-documenter emits HTML tables inside its markdown, plus `<!-- -->`
  // spacers and HTML-escaped angle brackets. That renders correctly as HTML but
  // is pure overhead for anything reading the ".md" mirror, so flatten it to
  // real markdown there. Hand-written pages are passed through untouched.
  const API_DOC_MARKER =
    "<!-- Do not edit this file. It is automatically generated by API Documenter. -->";

  // Only `<!-- -->` is markup inside a cell. A generic <...> strip would eat
  // literal placeholders that belong to the prose — `<prefix>:<name>`, `<T>`
  // and `<channel>` all appear in cells.
  const cell = (html) =>
    html
      .replace(/<!-- -->/g, "")
      .replace(/\s+/g, " ")
      .replace(/(?<!\\)\|/g, "\\|") // api-documenter pre-escapes union pipes
      .trim();

  const tableToMarkdown = (table) => {
    const head = [...table.matchAll(/<th>([\s\S]*?)<\/th>/g)].map((m) =>
      cell(m[1])
    );

    if (!head.length) {
      return table; // unrecognised shape — leave it alone
    }

    const rows = [...table.matchAll(/<tr>\s*<td>([\s\S]*?)<\/tr>/g)].map((m) =>
      m[1].split(/<\/td>\s*<td>/).map((c) => cell(c.replace(/<\/td>\s*$/, "")))
    );

    return `\n${[
      `| ${head.join(" | ")} |`,
      `| ${head.map(() => "---").join(" | ")} |`,
      ...rows.map((r) => `| ${r.join(" | ")} |`),
    ].join("\n")}\n`;
  };

  eleventyConfig.addFilter("agentMarkdown", (content) => {
    let out = String(content == null ? "" : content);
    const generated = out.includes(API_DOC_MARKER);

    // Hand-written pages embed <script type="application/ld+json"> for FAQPage
    // markup and, on one page, a behaviour script. Both are markup for a browser
    // and neither is content: in the ".md" mirror they arrive as a wall of raw
    // JSON (or JavaScript) before the prose, and any Liquid inside them is
    // unrendered, so the mirror asserted things like `"softwareVersion":
    // "{{ latest_rpc }}"`. The HTML page keeps them; the mirror never wants them.
    out = out
      .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "")
      .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "");

    out = out.replace(/<table>[\s\S]*?<\/table>/g, tableToMarkdown);

    if (generated) {
      out = out
        .split(API_DOC_MARKER)
        .join("") // an instruction to repo contributors, not to readers
        .replace(/<!-- -->/g, "")
        .replace(/&gt;/g, ">")
        .replace(/&lt;/g, "<")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&amp;/g, "&"); // last, so &amp;gt; does not become >
    }

    return out.replace(/\n{3,}/g, "\n\n").trim();
  });

  // ---- FAQPage, generated from the page's own FAQ section ------------------
  // The Q&A pairs were already written, already visible, and already shaped as
  // questions — and only two pages in the repo turned them into FAQPage markup,
  // by hand. Nine blog posts and /license/ had 55 answered questions between them
  // that no engine could read as questions.
  //
  // Generated from the source rather than hand-written for two reasons. Google
  // requires FAQPage answers to be PRESENT ON THE PAGE, and a hand-copied block
  // drifts from the prose the moment either is edited — the one that existed had
  // already normalised "What's" to "What is" and "don't" to "do not", so the
  // markup and the visible text were not the same strings. And 55 pairs is not
  // something to transcribe into JSON by hand once, let alone keep in step.
  //
  // Scoped deliberately narrowly: only `### `-level questions, only inside a
  // `## FAQ` / `## Frequently asked…` section, only when the heading ends in a
  // question mark, and only when the page has at least two of them. The repo has
  // two other FAQ shapes — <details>/<summary> pairs in one post, and question
  // headings scattered under ordinary sections in mcp/security.md — which this
  // deliberately does NOT match, so their existing hand-written blocks stay
  // correct and nothing is emitted twice.
  const inlineToText = (s) =>
    String(s)
      .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1") // links -> their text
      .replace(/`([^`]+)`/g, "$1")             // code spans
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/(^|\s)\*([^*]+)\*/g, "$1$2")
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();

  eleventyConfig.addFilter("faqPairs", (raw) => {
    const pairs = [];
    let inFaq = false;
    let question = null;
    let answer = [];

    const flush = () => {
      if (question && answer.length) {
        pairs.push({ q: question, a: inlineToText(answer.join(" ")) });
      }
      question = null;
      answer = [];
    };

    for (const line of String(raw == null ? "" : raw).split("\n")) {
      // Any H2 ends the previous answer and decides whether we are in the section.
      if (/^##\s/.test(line) && !/^###/.test(line)) {
        flush();
        inFaq = /^##\s+(FAQ|Frequently asked)/i.test(line);
        continue;
      }
      if (!inFaq) continue;

      const heading = line.match(/^###\s+(.+?)\s*$/);

      if (heading) {
        flush();
        question = inlineToText(heading[1]);
        continue;
      }
      if (!question) continue;
      // A blank line closes the answer: only the first paragraph after the
      // question is the answer, so a follow-up code block or aside is left out
      // rather than concatenated into one run-on string.
      if (line.trim() === "") {
        if (answer.length) flush();
        continue;
      }
      answer.push(line.trim());
    }
    flush();

    return pairs.filter((p) => p.q.endsWith("?"));
  });

  // Posts written by a given author slug (newest first).
  eleventyConfig.addFilter("byAuthor", (posts, slug) =>
    (posts || []).filter((p) => p.data.author === slug)
  );

  // Look up a single author record by slug from the authors data list.
  eleventyConfig.addFilter("authorBySlug", (authors, slug) =>
    (authors || []).find((a) => a.slug === slug)
  );

  // Related posts: others sharing the most `topics` with the current one,
  // newest first as the tie-breaker; falls back to filling with recent posts.
  eleventyConfig.addFilter("related", (posts, currentUrl, topics, limit) => {
    const want = new Set(topics || []);
    const others = (posts || []).filter((p) => p.url !== currentUrl);
    const scored = others
      .map((p) => ({
        p,
        score: (p.data.topics || []).filter((t) => want.has(t)).length,
      }))
      .sort((a, b) => b.score - a.score || b.p.date - a.p.date);
    const n = limit || 5;
    const picked = scored.filter((x) => x.score > 0).slice(0, n).map((x) => x.p);
    if (picked.length < n) {
      for (const x of scored) {
        if (picked.length >= n) break;
        if (!picked.includes(x.p)) picked.push(x.p);
      }
    }
    return picked;
  });

  // Reverse mesh: given a list of topics (declared by a docs/tutorial/cli area),
  // return the blog posts sharing the most topics, newest first. Drafts excluded.
  // Unlike `related` it does NOT backfill — a docs page only links posts that are
  // genuinely on-topic (empty result -> the "From the blog" block is omitted).
  eleventyConfig.addFilter("postsByTopics", (posts, topics, limit) => {
    const want = new Set(topics || []);
    if (!want.size) return [];
    return (posts || [])
      .filter((p) => !p.data.draft)
      .map((p) => ({ p, score: (p.data.topics || []).filter((t) => want.has(t)).length }))
      .filter((x) => x.score > 0)
      .sort((a, b) => b.score - a.score || b.p.date - a.p.date)
      .slice(0, limit || 4)
      .map((x) => x.p);
  });

  // Static assets: shared first, then the active edition's theme css (same /css dir).
  eleventyConfig.addPassthroughCopy({ "src/_shared/fonts": "fonts" });

  // CSS + JS are emitted under content-hashed filenames and referenced through the
  // `asset` filter, which is what lets /css/* and /js/* be cached immutably (see
  // scripts/lib/asset-manifest.js for the deploy bug this fixes, and
  // src/headers.liquid for the matching Cache-Control). Only hashed names are
  // written — no unhashed copy — so a wildcard immutable header cannot ever apply
  // to a mutable URL.
  for (const [from, to] of ASSETS.copies) {
    eleventyConfig.addPassthroughCopy({ [from]: to });
  }
  eleventyConfig.addGlobalData("assetManifest", ASSETS.manifest);

  // Resolve a logical asset URL ("/css/base.css") to its hashed one. Throws on an
  // unknown path rather than passing it through: a silent miss would emit a 404ing
  // stylesheet that renders as an unstyled page, and the link checker only sees
  // what the templates actually wrote.
  eleventyConfig.addFilter("asset", function (url) {
    const hashed = ASSETS.manifest[url];

    if (!hashed) {
      throw new Error(
        `asset filter: no hashed build of "${url}". ` +
          `Known: ${Object.keys(ASSETS.manifest).join(", ")}`,
      );
    }
    return hashed;
  });

  eleventyConfig.addPassthroughCopy({ "images": "images" });
  eleventyConfig.addPassthroughCopy({ [`src/${EDITION}/favicon.svg`]: "favicon.svg" });
  eleventyConfig.addPassthroughCopy({ [`src/${EDITION}/favicon.ico`]: "favicon.ico" });
  // robots.txt + sitemap.xml are generated per edition (see src/robots.liquid,
  // src/sitemap.liquid) so each domain advertises its own sitemap URL.

  // Per-edition _redirects (Cloudflare Pages). imqueue.com 301s legacy content
  // paths to imqueue.org; imqueue.org 301s retired versioned API URLs to /latest/.
  eleventyConfig.addPassthroughCopy({ [`src/${EDITION}/_redirects`]: "_redirects" });

  // API reference (current + kept archives) is now generated as native Eleventy
  // pages under src/org/api/**; the old standalone TypeDoc HTML passthrough is
  // gone. Regenerate with `npm run build-docs` (latest) / `gen-api-archive` (old).

  return {
    dir: {
      input: "src",
      output: OUTPUT,
      includes: "_shared/_includes",
      layouts: "_shared/_includes",
      data: "_data",
    },
    markdownTemplateEngine: "liquid",
    htmlTemplateEngine: "liquid",
  };
};
