// GENERATED by scripts/build-api-docs.js — do not edit by hand.
// Cloudflare Pages Function — /api/dd-trace/*
// Retired slug: 301s /api/dd-trace/… onto /api/datadog/latest/….
// See lib/api-redirects.js for the policy and why this is not in _redirects.
import { handleApiRequest } from "../../../lib/api-handler.js";

export const onRequest = handleApiRequest;
