// api-types.ts — the shapes the generated /api/ data modules carry.
//
// Hand-written on purpose, while the five modules that use it
// (api-versions, api-legacy-pages, api-crosslinks, api-renames, api-renamed)
// are all GENERATED by scripts/build-api-docs.ts. Keeping the types here means
// the generator emits one import line instead of re-emitting a type definition
// per file, and it gives api-redirects.ts a name to state its contract against.

/** What is published for one package: the current release, plus kept majors. */
export interface VersionPlan {
  /** Newest published version, the target of every /latest/ URL. */
  latest: string;
  /** Highest release of each past major that still has a version tree on disk. */
  archives: string[];
}

/**
 * Package slug -> version plan.
 *
 * The value is optional because every real lookup here is on an UNTRUSTED
 * segment out of a request path — `/api/<anything>/` — so a miss is the normal
 * case, not an error. Typing it as a bare Record would let `versions[pkg].latest`
 * type-check and then throw at the edge on the first bad URL a crawler invents.
 */
export type ApiVersions = Record<string, VersionPlan | undefined>;
