// GENERATED by scripts/build-api-docs.js — do not edit by hand.
//
// API pages whose URL moved because scripts/lib/api-model.js stripped an
// api-extractor collision suffix from the symbol's name — `Response_2` was never
// a name @imqueue/http-protect exports, it recorded a clash with an ambient
// declaration. The suffixed URL was published, so it 301s onto the real one
// instead of 404ing.
//
// Keys and values are <pkg>/<version-segment>/<page-basename>, i.e. the /api/
// path with no leading or trailing slash.
export const RENAMED_API_PAGES = new Map([
    ["pg-cache/latest/pg-cache.classdecorator_2", "pg-cache/latest/pg-cache.classdecorator"], // TypeAlias
    ["pg-cache/latest/pg-cache.methoddecorator_2", "pg-cache/latest/pg-cache.methoddecorator"], // TypeAlias
]);
