// GENERATED by scripts/build-api-docs.ts — do not edit by hand.
//
// Packages published under a different name once, retired slug -> current slug.
// Source of truth: RENAMED_PACKAGES in scripts/lib/api-packages.ts.
export const RENAMED_PACKAGES: ReadonlyMap<string, string> = new Map([
  ["opentelemetry-instrumentation-imqueue", "opentelemetry"],
  ["sequelize", "pg-sequelize"],
  ["dd-trace", "datadog"],
]);
