// GENERATED by scripts/build-api-docs.ts — do not edit by hand.
// Cloudflare Pages Function — /api/core/*
// Resolves retired @imqueue/core version URLs onto the kept version trees.
// See lib/api-redirects.ts for the policy and why this is not in _redirects.
import { handleApiRequest } from "../../../lib/api-handler.ts";

export const onRequest = handleApiRequest;
